### PR TITLE
Fixing the issue that requests may not be sent due to cache of fetch

### PR DESCRIPTION
**Pull request by shihshen**
I finally figure out why some requests may not be sent out. [Here](https://stackoverflow.com/questions/59289168/chrome-extension-fetch-not-refetching) is the reference.
However, this fix does break 2 unit test cases. I can also try to fix the test cases if you prefer.

### CODE REVIEW

**Comment by luciopaiva** [comment]
Hmm, so it was a caching problem. Nice catch!

About the tests, no problem. I fixed them [here](https://github.com/luciopaiva/witchcraft/pull/38). I am gonna close your PR in favor of the new one.

Which web server are you using to serve your script? Is it [Web Server for Chrome](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb) or a custom one?

I never had cache problems with that app, so I believe you might be using a different server.

**Comment by shihshen** [comment]
I tried web server for chrome and node static. had the same issue with both.

**Comment by luciopaiva** [comment]
What's your OS?

**Comment by shihshen** [comment]
I am using Mac, however, one of my friends who is using windows and web server for chrome is having the same issue.

**Pull request closed without merging**
